mytestkey=This value is from LOCAL properties file

paypal.client.id=AdVlwh6z1I-AbIjwocWHDi2v9f1UQvCWBP-AwTvLabfrql5YFhwzaT1YmWOsI2lSScCJO7bbKM4dfhpA
paypal.client.secret=EDauw-seqreohGlP1mBmFWkK1uVNqi-LeIBAJrKUMC8x9t7ilayjsBB9s_uj2cozUNHK8b6STan1zVDg

paypal.oauth.token.url=https://api.sandbox.paypal.com/v1/oauth2/token
paypal.create.order.url=https://api.sandbox.paypal.com/v2/checkout/orders
paypal.capture.order.url=https://api-m.sandbox.paypal.com/v2/checkout/orders/{id}/capture